# Generated by Django 5.1.3 on 2025-08-18 19:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('file', models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(['mp4'])])),
                ('platforms', models.TextField(choices=[('Yt', 'Youtube')])),
            ],
        ),
    ]
