# Generated by Django 5.1.3 on 2025-08-18 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_uploader_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videopost',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
