# Generated by Django 5.1.3 on 2025-08-18 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_uploader_app', '0002_alter_videopost_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videopost',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='videopost',
            name='platforms',
            field=models.TextField(choices=[('Yt', 'Youtube')], default='Yt'),
        ),
        migrations.AlterField(
            model_name='videopost',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
